# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Quiz_GUI_QT6.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QButtonGroup, QLabel, QMainWindow,
    QMenuBar, QPlainTextEdit, QPushButton, QRadioButton,
    QSizePolicy, QStackedWidget, QStatusBar, QTextEdit,
    QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(618, 457)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.pageHome = QWidget()
        self.pageHome.setObjectName(u"pageHome")
        self.label = QLabel(self.pageHome)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 30, 521, 41))
        font = QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.txtTopic = QTextEdit(self.pageHome)
        self.txtTopic.setObjectName(u"txtTopic")
        self.txtTopic.setGeometry(QRect(150, 90, 301, 64))
        self.label_2 = QLabel(self.pageHome)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 100, 111, 41))
        self.label_2.setFont(font)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_3 = QLabel(self.pageHome)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 170, 111, 41))
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.txtMaxLength = QTextEdit(self.pageHome)
        self.txtMaxLength.setObjectName(u"txtMaxLength")
        self.txtMaxLength.setGeometry(QRect(150, 180, 301, 31))
        self.btnConfirm = QPushButton(self.pageHome)
        self.btnConfirm.setObjectName(u"btnConfirm")
        self.btnConfirm.setGeometry(QRect(320, 260, 81, 26))
        font1 = QFont()
        font1.setPointSize(12)
        self.btnConfirm.setFont(font1)
        self.btnClear = QPushButton(self.pageHome)
        self.btnClear.setObjectName(u"btnClear")
        self.btnClear.setGeometry(QRect(170, 260, 81, 26))
        self.btnClear.setFont(font1)
        self.stackedWidget.addWidget(self.pageHome)
        self.pageLoading = QWidget()
        self.pageLoading.setObjectName(u"pageLoading")
        self.stackedWidget.addWidget(self.pageLoading)
        self.pageQuiz = QWidget()
        self.pageQuiz.setObjectName(u"pageQuiz")
        self.lblQuestion = QLabel(self.pageQuiz)
        self.lblQuestion.setObjectName(u"lblQuestion")
        self.lblQuestion.setGeometry(QRect(80, 40, 471, 51))
        self.lblQuestion.setFont(font)
        self.lblQuestion.setTextFormat(Qt.TextFormat.RichText)
        self.lblQuestion.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.btnQuit = QPushButton(self.pageQuiz)
        self.btnQuit.setObjectName(u"btnQuit")
        self.btnQuit.setGeometry(QRect(80, 290, 81, 26))
        self.btnQuit.setFont(font1)
        self.btnNext = QPushButton(self.pageQuiz)
        self.btnNext.setObjectName(u"btnNext")
        self.btnNext.setGeometry(QRect(270, 250, 81, 26))
        self.btnNext.setFont(font1)
        self.btnBack = QPushButton(self.pageQuiz)
        self.btnBack.setObjectName(u"btnBack")
        self.btnBack.setGeometry(QRect(80, 250, 81, 26))
        self.btnBack.setFont(font1)
        self.radioButton_3 = QRadioButton(self.pageQuiz)
        self.buttonGroup_1 = QButtonGroup(MainWindow)
        self.buttonGroup_1.setObjectName(u"buttonGroup_1")
        self.buttonGroup_1.addButton(self.radioButton_3)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(80, 170, 200, 24))
        self.radioButton_3.setFont(font)
        self.radioButton_4 = QRadioButton(self.pageQuiz)
        self.buttonGroup_1.addButton(self.radioButton_4)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setGeometry(QRect(80, 200, 200, 24))
        self.radioButton_4.setFont(font)
        self.radioButton_1 = QRadioButton(self.pageQuiz)
        self.buttonGroup_1.addButton(self.radioButton_1)
        self.radioButton_1.setObjectName(u"radioButton_1")
        self.radioButton_1.setGeometry(QRect(80, 110, 200, 24))
        self.radioButton_1.setFont(font)
        self.radioButton_2 = QRadioButton(self.pageQuiz)
        self.buttonGroup_1.addButton(self.radioButton_2)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(80, 140, 200, 24))
        self.radioButton_2.setFont(font)
        self.btnSubmit = QPushButton(self.pageQuiz)
        self.btnSubmit.setObjectName(u"btnSubmit")
        self.btnSubmit.setGeometry(QRect(270, 290, 81, 26))
        self.btnSubmit.setFont(font1)
        self.label_5 = QLabel(self.pageQuiz)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(80, 10, 211, 21))
        self.lblProgress = QLabel(self.pageQuiz)
        self.lblProgress.setObjectName(u"lblProgress")
        self.lblProgress.setGeometry(QRect(80, 10, 471, 21))
        self.lblProgress.setFont(font1)
        self.lblProgress.setTextFormat(Qt.TextFormat.RichText)
        self.lblProgress.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.stackedWidget.addWidget(self.pageQuiz)
        self.pageResults = QWidget()
        self.pageResults.setObjectName(u"pageResults")
        self.btnTryNew = QPushButton(self.pageResults)
        self.btnTryNew.setObjectName(u"btnTryNew")
        self.btnTryNew.setGeometry(QRect(170, 270, 81, 26))
        self.btnTryNew.setFont(font1)
        self.btnTrySame = QPushButton(self.pageResults)
        self.btnTrySame.setObjectName(u"btnTrySame")
        self.btnTrySame.setGeometry(QRect(50, 270, 81, 26))
        self.btnTrySame.setFont(font1)
        self.label_4 = QLabel(self.pageResults)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(50, 200, 241, 20))
        self.label_4.setFont(font)
        self.btnQuit_2 = QPushButton(self.pageResults)
        self.btnQuit_2.setObjectName(u"btnQuit_2")
        self.btnQuit_2.setGeometry(QRect(50, 320, 71, 26))
        self.btnQuit_2.setFont(font1)
        self.txtResults = QPlainTextEdit(self.pageResults)
        self.txtResults.setObjectName(u"txtResults")
        self.txtResults.setGeometry(QRect(50, 50, 461, 141))
        self.stackedWidget.addWidget(self.pageResults)

        self.verticalLayout.addWidget(self.stackedWidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 618, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Please enter the topic for this quiz:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Topic:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Max Length:", None))
        self.btnConfirm.setText(QCoreApplication.translate("MainWindow", u"Confirm", None))
        self.btnClear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.lblQuestion.setText("")
        self.btnQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.btnNext.setText(QCoreApplication.translate("MainWindow", u"Next", None))
        self.btnBack.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.radioButton_3.setText("")
        self.radioButton_4.setText("")
        self.radioButton_1.setText("")
        self.radioButton_2.setText("")
        self.btnSubmit.setText(QCoreApplication.translate("MainWindow", u"Submit", None))
        self.label_5.setText("")
        self.lblProgress.setText("")
        self.btnTryNew.setText(QCoreApplication.translate("MainWindow", u"New set", None))
        self.btnTrySame.setText(QCoreApplication.translate("MainWindow", u"Same set", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Try again?", None))
        self.btnQuit_2.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
    # retranslateUi

